NUMPY ARRAY

In [3]:
import numpy as np


In [4]:
mylist =[1,2,3]

In [5]:
type(mylist)

list

In [6]:
np.array(mylist)
#doesn't effect the orginal list

array([1, 2, 3])

In [7]:
myarr = np.array(mylist)

In [8]:
myarr

array([1, 2, 3])

In [9]:
type(myarr)

numpy.ndarray

In [10]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [11]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10,2)
#go from 0 to 10 with step of 2 -> exclusive of 10

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.linspace(0,10,8)

# gives evenly spaced number over a specified range of numbers -> 
# start,end, how many numbers we want  & 10 is inclusive

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [18]:
np.eye(3) #gives identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.rand(3)

# gives random uniform numbers between inclusive 0 n exclusive 1

array([0.4712865 , 0.13656915, 0.45751543])

In [20]:
np.random.randn(5,2)
#gives random number from standard distribution i.e mean is 0 n varaince is 1

array([[ 0.28424589,  0.0819523 ],
       [-0.608096  ,  1.80206083],
       [-0.28000037,  0.64082365],
       [ 0.08279207,  1.14302241],
       [ 0.52916054, -0.53394237]])

In [21]:
np.random.randint(0,101,(3,4))
#gives random integers inclusive of lower level n exclusive of higher one

array([[ 91,  96,  53,  10],
       [ 15,  70,  94,  65],
       [100,   6,  77,  87]])

In [22]:
np.random.seed(412) #helps to set a particular set of random numbers
np.random.rand(4)

array([0.94496726, 0.88124296, 0.03290492, 0.58412749])

In [23]:
arr = np.arange(0,25)

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr = np.random.randint(0,101,10)

In [26]:
ranarr

array([74, 33, 49, 21, 47, 84, 84, 35, 16, 86])

In [27]:
ranarr.max()

86

In [28]:
ranarr.min()

16

In [29]:
ranarr.argmax()

9

In [30]:
ranarr.argmin()

8

In [31]:
ranarr.dtype

dtype('int32')

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.shape

(25,)

In [34]:
arr=arr.reshape(25,)

In [35]:
arr.shape

(25,)

In [36]:
arr[8]

8

In [37]:
arr[1:5]

array([1, 2, 3, 4])

In [38]:
arr[:5]

array([0, 1, 2, 3, 4])

In [39]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr[0:5]=100

In [42]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [43]:
arr=np.arange(0,11)

In [44]:
slice_of_arr=arr[0:5]

In [46]:
slice_of_arr[:]=99

In [47]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [48]:
arr_copy=arr.copy()

In [49]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [50]:
arr_copy[:]=100

In [51]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [52]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [54]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [55]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
arr_2d.shape

(3, 3)

In [57]:
arr_2d[0]

array([ 5, 10, 15])

In [59]:
arr_2d[1,1]
#or arr_2d[1][1]

25

In [61]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [62]:
arr=np.arange(1,11)

In [63]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [65]:
bool_arr = arr>4

In [66]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [67]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [68]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [69]:
arr +5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [70]:
arr-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [71]:
arr +arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [72]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [74]:
arr.sum()

55

In [75]:
arr.mean()

5.5

In [76]:
arr.var()

8.25

In [77]:
arr.std()

2.8722813232690143

In [79]:
new=np.arange(0,16).reshape(4,4)

In [80]:
new

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
new.sum()

120

In [85]:
new.sum(axis=1)

array([ 6, 22, 38, 54])